// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRf1nJQT9QfluPJ7GQhJy4Sz_fuw9UWI',
    appId: '1:923766598429:android:8c89238bc6d4b52a3e4ff4',
    messagingSenderId: '923766598429',
    projectId: 'salon-customer-6c286',
    databaseURL: 'https://salon-customer-6c286-default-rtdb.firebaseio.com',
    storageBucket: 'salon-customer-6c286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJS8Y-L-L3Pa2sFq37QIUWodBNc0_IvO8',
    appId: '1:923766598429:ios:be1aefc009dae2143e4ff4',
    messagingSenderId: '923766598429',
    projectId: 'salon-customer-6c286',
    databaseURL: 'https://salon-customer-6c286-default-rtdb.firebaseio.com',
    storageBucket: 'salon-customer-6c286.appspot.com',
    iosClientId: '923766598429-cln65h33938l5ipjri55f7grqu9u5avc.apps.googleusercontent.com',
    iosBundleId: 'com.creativitySol.salon',
  );
}
